name: Snyk Security Check

on: [push,pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: pnpm install --frozen-lockfile
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}